export class BasicConstants{
  static readonly FULL_WIDTH:string = '100%'
  static readonly FULL_HEIGHT:string = '100%'
  static readonly FONT_SIZE_XSMALL:number = 12
  static readonly FONT_SIZE_SMALL:number = 14
  static readonly FONT_SIZE_NORMAL:number = 16
  static readonly FONT_SIZE_LARGE:number = 20
  static readonly FONT_SIZE_XLARGE:number = 30
  static readonly MAIN_TAB_BAR_HEIGHT:number = 60
  static readonly TOASTDURATION:number = 1000
  static readonly BASE_URL:string = 'http://localhost:3000'
}